on: push
name: deploy
jobs:
  deploy:
    environment: main
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          logout: true
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        repository: jufcontrerasco/test-git-action
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
        push: true
